### ISSUE TITLE
Command '1Password: Get from 1Password' resulted in an error (Cannot read properties of undefined (reading 'kind'))

### ISSUE THREAD

**Issue by hoium** [1Password/op-vscode#1]
## I'm unable to Get from 1Password

**Steps:**

- Open Command Palette
- Run `>1Password: Get from 1Password`
- Enter in Name or ID

<img width="311" alt="2022-06-07_14-21-15" src="https://user-images.githubusercontent.com/9096615/172455255-d8c98e3c-cb94-4316-8abd-8c22af865b8b.png">

**Comment by hoium** [comment]
Hey @jodyheavener  - That is correct ;) 

```
sw_vers                                                                                                                                                                                                                         

ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

```
code -v
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
arm64
```

```
op -v
2.4.0
```

**Comment by jodyheavener** [comment]
Hey @hoium, while I haven't been able to identify your specific issue I did make some changes to the underlying CLI wrapper library recently, and they should be present in v0.1.2 of the extension. Can you confirm if this issue is still occurring?

If so, some clarifying questions:

- Does this happen for every item, or just some?
- [Hovering a secret reference](https://developer.1password.com/docs/vscode/#inspect-and-preview-secret-references) to retrieve item/field details performs a similar action in the background; does this also fail for you?
