### ISSUE TITLE
Error executing CLI command: invalid JSON in piped input.

### ISSUE THREAD

**Issue by HenkieThee** [1Password/op-vscode#187]
op-vscode version: 1.0.4

VS Code version: 1.84.2

CLI version: 2.22.0

OS: WIndows

## Steps to reproduce

Trough the command palleto trying to execute generate or store password both give the same error well other commands are working like select account etc also the commands like op vault list etc works in the terminal but like those 2 command will not work from the command pallete and this is the error i get: Error executing CLI command: invalid JSON in piped input.

**Comment by Aidan-Chey** [comment]
I just attempted to get the VSCode plugin working also and am hitting the same errors for the same actions. Unfortunately the plugin logs aren't any more descriptive than the error. Even enabling debug in the CLI doesn't seem to help, but i suspect that wouldn't work because of scope issues.

I've chosen the account and vault in vsCode.

Retrieving item details using the plugin seems to work, I was able to retrieve a username using the item's private link.

extension version: 1.0.4
CLI version: 2.27.0
Windows 11, version 23H2
VSCode details:
> Version: 1.88.1 (system setup)
> Commit: e170252f762678dec6ca2cc69aba1570769a5d39
> Date: 2024-04-10T17:41:02.734Z
> Electron: 28.2.8
> ElectronBuildId: 27744544
> Chromium: 120.0.6099.291
> Node.js: 18.18.2
> V8: 12.0.267.19-electron.0
> OS: Windows_NT x64 10.0.22631

**Comment by jodyheavener** [comment]
Hi all, doing some issue triage. As far as I can tell I believe this issue has the same underlying cause as this one: https://github.com/1Password/op-vscode/issues/100

I am going to close this for now as I have a release coming out soon. Please keep an eye out for updates in the other ticket. If this issue persists after the next release please feel free to re-open. Thank you!
